"""latest_schema

Revision ID: 8dfa904bbc0a
Revises: 8f27c5be7992
Create Date: 2026-07-14 07:47:05.388769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfa904bbc0a'
down_revision = '8f27c5be7992'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
